### ISSUE TITLE
Sodium Extras adaptive vsync support

### ISSUE THREAD

**Issue by Titaniumtown** [not-coded/WayFix#2]
When this mod is installed, the "adaptive" option for vsync on sodium extras is absent. I have a freesync display and am unable to use this mod and also have adaptive sync.

W/o wayfix:
![image](https://github.com/user-attachments/assets/b7df2ec3-2382-43cd-86e0-3d2d6cd5aa0a)

w/ wayfix:
![image](https://github.com/user-attachments/assets/6c8f8d9b-ff7b-46fc-a551-7dbd1557d2a2)

**Comment by not-coded** [comment]
The adaptive option for VSync is from **Sodium Extras**, not Sodium.
https://github.com/FlashyReese/sodium-extra-fabric/blob/1.21/dev/common/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/vsync/MixinSodiumGameOptionsPages.java#L47

The reason why Adaptive VSync isn't there seems to be because Wayland GLFW not supporting `GLX_EXT_swap_control_tear` and `WGL_EXT_swap_control_tear`.
https://github.com/FlashyReese/sodium-extra-fabric/blob/1.21/dev/common/src/main/java/me/flashyreese/mods/sodiumextra/mixin/adaptive_sync/MixinWindow.java#L18

Forcing Sodium Extras to use Adaptive Sync logs that exact message in the console:
![image](https://github.com/user-attachments/assets/73bf5bfd-e313-4932-9fbd-d06d5f3521af)
![image](https://github.com/user-attachments/assets/bb4c3246-cb3a-45c8-9c30-644dc867381e)

**Comment by Titaniumtown** [comment]
Oh thanks for the correction! Interesting find. So it's an upstream GLFW issue then. Thanks!
